[유저 / 학습] Locale 적용 관련 데이터 관리 로직 변경 및 추가
MakeFrog/TechTalk pull request #109
Opened 2024-07-25 16:42 UTC by Xim-ya

## 📝 변경 내용
- <a href="https://github.com/MakeFrog/TechTalk/commit/88638f9ca36eb0ab277356c1aa353bbe8aa97243">Locale 관련 캐싱 레이어 추가 (SystemLocalDataSource)</a>
- <a href="https://github.com/MakeFrog/TechTalk/commit/b398b593aa16140b0a60f36dee5fc0124a8f9723">AppLocale 모듈 추가</a>
- <a href="https://github.com/MakeFrog/TechTalk/commit/dd5b3a228fa75fea0b8df5b62bbddf23f81e4634">DB에 유저 locale 정보를 저장하는 로직 추가</a>

</br>

## 🔍 상세

### Locale 관련 캐싱 레이어
유저의 locale 정보를 저장하는 데이터 레이어를 추가하였습니다. (SystemLocalDataSource)
locale 정보뿐만 아니라 필요 시 시스템상 로컬에 저장되어야 하는 데이터를 추가할 수 있습니다.

### AppLocale 모듈
```dart
abstract final class AppLocale {
  static Locale get currentLocal {
    /// 현재 context로부터 locale을 가져올 수 없다면 Local Storage에 저장된 값을 가져옴.
    /// [NOTE]
    /// 이런 경우는 거의 발생하지 않겠지만.. 혹시 모를 안전장치
    if (rootNavigatorKey.currentContext == null) {
      final languageCode =
          AppLocal.systemBox.get(AppLocal.systemBox)?.languageCode ??
              Localization.en.locale.languageCode;

      return Localization.getMatchedLocalization(languageCode).locale;
    }

    return rootNavigatorKey.currentContext!.locale;
  }

  ///
  /// locale 정보 반환 메소드
  ///
  static String getLocaleName() {
    return Platform.localeName;
  }

  bool get isKo => currentLocal.languageCode == 'ko';

  bool get isEn => currentLocal.languageCode == 'en';
}
```
앱에서 사용되는 Locale 정보를 관리하는 모듈을 만들었습니다. 해당 모듈을 레이어 구분 없이 사용할 수 있도록 내부적으로 합의하면 좋을 것 같아요.

### 캐싱된 면접 데이터를 locale이 변경되었을 때 초기화
앱에서는 각 면접 주제의 질문과 답변 데이터를 로컬에 캐싱하여 빠르게 필요한 데이터에 접근할 수 있도록 하고 있습니다. 앱에서 유저가 언어 선택을 변경하여 locale 값이 변경되었을 때 기존 캐싱된 질문과 답변 데이터를 초기화하는 로직을 추가하였습니다.

### DB에 유저 locale 정보를 저장하는 로직
![ai](https://github.com/user-attachments/assets/e5674198-083b-4aa6-8463-d2a31ee6e521)

데이터베이스에 유저의 locale 정보를 저장하는 로직을 추가하였습니다. 이후에 유저의 나라 정보를 통계 낼 때 유용할 것 같아요.

<br/>

👥 리뷰어
@Yellowtoast, @yundal8755

<br/>

📌 기타 사항
없음

2024-07-27 03:22 UTC, Yellowtoast commented on lib/features/system/data_source/local/boxes/system_box.dart
> +class SystemBox extends HiveObject {
만약에 locale 정보를 변경하는 기능을 넣지 않는다면 context를 통해 무조건 접근하도록 하도록 통일하는 것도 괜찮아보이는데, 혹시 언어 변경 기능이 추가될 수도 있을 것이라고 생각하셔서 해당 정보를 local에 저장하도록 구현하신 걸까요? 해당 경우에 local을 먼저 확인한 뒤 context를 살피는게 좋을까요? 아니면 context를 우선적으로 살피고 local과 비교 후 업데이트 해주는 방식이 좋을까요?

2024-07-27 03:22 UTC, Yellowtoast commented on lib/features/system/data_source/local/boxes/system_local_data_source_impl.dart
> +  Future<String?> loadLocaleCode() async {
LocaleCode와 LanguageCode의 용어가 명확히 구분되면 좋을 것 같습니다!
Locale(ko, "KR") 앞이 languageCode, 뒤가 countryCode로 알고 있는데 LocaleCode라고 하면 자칫 두가지가 혼동될 수도 있을 것 같아요!

2024-07-27 03:22 UTC, Yellowtoast commented on lib/app/localization/app_locale.dart
> +          AppLocal.systemBox.get(AppLocal.systemBox)?.languageCode ??
context의 languageCode와 로컬에 저장된 languageCode가 다를 경우 업데이트 해주는 로직도 필요할 것 같아요! main에 추가하면 좋을까요?

2024-07-27 03:32 UTC, Yellowtoast commented on lib/app/localization/app_locale.dart
> +abstract final class AppLocale {
해당 경우에는 provider를 사용하지 않고 따로 이런 클래스로 빼신 이유가 있을까요?
유연하게 사용할 수 있는 점은 좋지만, localization 은 context에 크게 영향을 받는 영역이라 차라리 keepAlive한 provider로 사용하는 쪽이 좋지 않을까 생각도 해봅니다! 혹시나 나중에 휴대폰 기본 설정은 한국어를 사용하지만 언어 변경 UI를 원하는 유저가 생겨날 수도 있을 것 같아서요. (예를 들면 해외 취업을 준비하는 개발자)

2024-07-27 04:23 UTC, Xim-ya commented on lib/features/system/data_source/local/boxes/system_box.dart
> +class SystemBox extends HiveObject {
locale 정보를 앱 내에서 변경하는 기능을 추가하지 않더라도 앱 설정에서는 변경할 수 있어서 locale 로컬 스토리지에 저장하는 로직을 추가하였습니다!

만약 한국어로 locale이 설정된 유저가 앱 설정에서 영어로 locale을 변경했을 때,
학습탭의 면접 질문과 답변은 여전히 캐싱된 한국어 버전의 데이터셋이 남아있게 됩니다.

이런 경우를 방지하고자 마지막 locale 정보를 로컬 스토리지에 저장하고, 학습탭에 진입했을 때 locale 정보가 변경되었다면 기존 캐싱된 데이터를 삭제하는 로직을 추가하였습니다.

2024-07-27 04:26 UTC, Xim-ya commented on lib/features/system/data_source/local/boxes/system_local_data_source_impl.dart
> +  Future<String?> loadLocaleCode() async {
그렇네요!

loadLocalLanguageCode로 변경하였습니다.
https://github.com/MakeFrog/TechTalk/pull/109/commits/e8bc3651a9c95d8c4b6947e965d8f15a0adc9496

감사합니다:)

2024-07-27 04:28 UTC, Xim-ya commented on lib/app/localization/app_locale.dart
> +          AppLocal.systemBox.get(AppLocal.systemBox)?.languageCode ??
```dart
  @override
  Future<Result<Locale?>> getStoredLocale() async {
    try {
      final code = await _localDataSource.loadLocaleLanguageCode();

      if (code == null) {
        final currentLocaleCode = AppLocale.currentLocal.languageCode;
        unawaited(_localDataSource.storeLocaleCode(currentLocaleCode)); <-- locale 크드 저장!

        return Result.success(null);
      }

      return Result.success(
        Localization.getMatchedLocalization(code).locale,
      );
    } on Exception catch (e) {
      return Result.failure(e);
    }
  }
```

SystemRepository에서 해당 기능을 추가하였습니다. locale 정보 저장 로직을 어디서 관리할지 고민을 했었는데... 데이터 조작 로직은 최대한 데이터 레이어에서 관리하는게 좋을 것 같아서 repository에 추가하였습니다.

2024-07-27 04:34 UTC, Xim-ya commented on lib/app/localization/app_locale.dart
> +abstract final class AppLocale {
AppLocale 모듈을 만든 가장 큰 핵심 이유는 dataSource 레이어에서 현재 설정된 locale에 따라 api call을 분기하기 위해서 입니다.

물론 api 호출 부분에서 현재 locale값을 인자로 넘겨줄 수 있겠지만 그렇게 된다면 eventMixin -> repsotiroy -> dataSource에 걸쳐 매번 locale 값을 전달해야되는 번거로움이 생길 것 같아서요.

물론 KeepAlive Provider로 만들어서 위에 문제를 해결할 수 있겠지만, 현재 dataSource에서는 ref에 접근하지 못하는 문제점이 있습니다.


그리고 AppLocale의 currentLocale getter 메소드는 현재 context로부터 locale 값을 우선적으로 먼저 가져오기 때문에,
```
혹시나 나중에 휴대폰 기본 설정은 한국어를 사용하지만 언어 변경 UI를 원하는 유저가 생겨날 수도 있을 것 같아서요. (예를 들면 해외 취업을 준비하는 개발자)
```
말씀하신 위와 같은 문제는 발생하지 않을 것 같아요!

2024-07-27 06:50 UTC, Yellowtoast commented on lib/app/localization/app_locale.dart
> +abstract final class AppLocale {
답변 감사합니다! 말씀하신 것처럼 context기반으로 관리하기 때문에 언어 변경 후 context를 refresh해준다면 추후의 데이터 레이어에서의 호출 역시 큰 문제가 없을 것으로 보이네요. 

다만 각각의 레이어에서 직접 AppLocale 에 접근하여 언어 코드를 가져오는 부분에 대해서는 만나서 더 이야기 나눠보면 좋을 것 같습니다!

2024-07-27 06:54 UTC, Yellowtoast commented on lib/features/system/data_source/local/boxes/system_box.dart
> +class SystemBox extends HiveObject {
넵 감사합니다!

2024-07-27 06:54 UTC, Yellowtoast approved these changes

2024-07-27 07:29 UTC, yundal8755 commented on lib/features/system/data_source/local/boxes/system_box.dart
> +class SystemBox extends HiveObject {
내용 확인했습니다 고생하셨어요!

2024-07-27 07:36 UTC, yundal8755 approved these changes

2024-07-27 08:03 UTC, Yellowtoast requested changes

2024-07-27 08:03 UTC, Yellowtoast commented on lib/app/localization/app_locale.dart
> +          AppLocal.systemBox.get(AppLocal.systemBox)?.languageCode ??
AppLocal.systemBox.get(AppLocal.systemBox)
get 안에 key 값이 들어가야 할 것 같은데 AppLocal.systemBoxName  넣어야 하는거 아닌가요?😯

2024-07-28 03:42 UTC, Xim-ya commented on lib/app/localization/app_locale.dart
> +          AppLocal.systemBox.get(AppLocal.systemBox)?.languageCode ??
어... 왜 이렇게 했지

확인 감사합니다 😂

https://github.com/MakeFrog/TechTalk/pull/109/commits/e3fc0b9b265b41376e3732e3b590d856a9050677

수정했습니다!

2024-07-29 01:26 UTC, Yellowtoast approved these changes

2024-07-29 01:27 UTC, Yellowtoast commented
확인했습니다!! 머지 부탁드립니다~! ㅎㅎ

2024-07-29 01:31 UTC, merged