Feat: [영상학습/면접] 영상학습과 면접에 필요한 엔티티 정의
MakeFrog/TechTalk pull request #138
Opened 2024-10-19 11:12 UTC by Yellowtoast

## 📝 변경 내용
* https://github.com/MakeFrog/TechTalk/issues/137

<br>

## 🔍 변경 이유
* 영상학습과 면접에 필요한 엔티티를 우선적으로 정의합니다.

<br>

## 🌍 영향
* 기존 QnaEntity 에 questionInstruction 이라는 필드가 추가되었습니다.

<br>

## 👥 리뷰어
* @Xim-ya @yundal8755 

<br>

## 📌 봐주셨으면 하는 사항
* Job 과 JobGroup 두가지 동일한 enum 이 있던데 하나는 지워도 되는걸까요? @Xim-ya 
* 폴더 구조 괜찮은지, 네이밍 괜찮은지 한번 봐주셨으면 합니다.
* 속도를 위하여 Overview, Detail을 각각 다른 도큐먼트로 저장하고, 정합을 위해 Cloud Functions를 사용하는 것에 관한 의견

<br>

2024-10-20 13:36 UTC, Xim-ya requested changes
수고하셨습니다!

2024-10-20 13:36 UTC, Xim-ya commented on lib/features/study_contents/repositories/entities/interface/contents_detail_entity.dart
> +  final Set<ContentsLanguage> contentsLanguage;
## Set Collection 사용

Set으로 중복 원소를 포함시키지 않도록 설계하신게 좋네요👍

기존에 중복 원소를 허용하지 않지만 List으로 선언한 entity 멤버 변수도 나중에 일괄 Set으로 적용해도 좋을 것 같습니다.

덕분에 하나 배웁니다!

2024-10-20 13:36 UTC, Xim-ya commented on lib/features/study_contents/repositories/entities/video_contents_author_entity.dart
> +}
## P2 추상 클래스 적용 이유

VideoContentsAuthorEntity의 멤버 변수는 추상 클래스인 ContentsAuthorEntity와 완전히 동일한것으로 보이는데, 별도로 ContentsAuthorEntity을 implement하는 구조로 설계하신 이유가 있을까요?

혹시 추후 적용될 가능성이 있는 '기술 블로그 컨텐츠 기반 면접 및 요약 기능'을 고려하여 entity를 추상하신거라면,
아직 상세 기능이나 요구사항이 주어진것이 하나도 없기 때문에 오히려 미리 추상화시키는게 복잡해질 수 있을 것 같아요.

만약 운이 좋게 추후에 '기술 블로그' entity가 공통적으로 추상화할 부분이 있으면 다행이지만, 반대의 경우 기존 추상 클래스를 걷어내는 로직이 작업이 불필요하게 있을 것 같아서요!

2024-10-20 13:36 UTC, Xim-ya commented on lib/features/study_contents/repositories/entities/video_contents_detail_entity.dart
> +}
## P1 비동기 호출 지연을 고려한 entity 구조 분리 

VideoContentsDetailEntity는 유튜브 면접 상세 페이지에 사용되는 엔티티를 설계할 때, 아래 두 가지 유형의 데이터를 유형을 구분할 필요가 있어 보이는데요.

#### Firestore에서 받아오는 데이터
```dart
  @override
  String id;

  @override
  final String title;

  @override
  final Set<SkillEntity> relatedSkills;

  @override
  final Set<JobGroup> relatedJobs;

  @override
  final Set<ContentsLanguage> contentsLanguage;
```
#### youtube_explore 패키지를 통해 받아오는 데이터
```dart
  /// 비디오 컨텐츠의 저자
  final VideoContentsAuthorEntity author;

  /// 비디오 조회수
  final int views;

  /// 비디오 길이
  final Duration videoLength;

  /// 비디오 좋아요 수
  final int likes;
```
youtube_explore 패키지를 통해 데이터를 구분해야 하는 이유는, 해당 패키지를 사용해 비동기적으로 데이터를 가져올 때 꽤 많은 로딩 시간이 소요되기 때문입니다. 심지어 관련 데이터를 가져올 때 많은 리소스를 필요로 하기 때문에 높은 확률로 'jank' 현상이 발생할 수 있으며, 이 때문에 비동기 호출 로직을 별도의 isolate로 처리하는 작업도 필요합니다.

> 이러한 문제 때문에 이전에 isolate을 쉽게 적용할 수 있는 패키지를 만들었으니 참고하시길 바랍니다.
[easy_isolate_mixin](https://pub.dev/packages/easy_isolate_mixin)

따라서, 현재 엔티티 구조로 데이터를 받는다면 youtube_explore 패키지를 통해 데이터를 fetch하는 시간이 길어지면서 화면 진입 시 로딩 시간이 길어진다는 문제점이 발생할 수 있씁니다.

또한 Firestore에서 데이터를 성공적으로 받아왔더라도, youtube 데이터를 가져오는 과정에서 예외가 발생할 경우, 정상적으로 받아온 데이터를 화면에 표시하지 못하는 문제도 발생할 수 있습니다.

이 문제를 어떻게 해결할지 함께 고민해주시면 좋을 것 같아요!

그리고 현재 유튜브 면접 상세 페이지는 '영상 요약' 탭과 '면접' 탭으로 구성되어 있으며, '영상 요약' 탭이 기본 인덱스로 설정되어 있습니다. 첫 화면에서 로딩된 데이터를 조금 더 빨리 보여주기 위해, 각 탭에 맞춰 데이터를 부분적으로 불러오는 방식도 고려해보면 좋을 것 같습니다.

ex) 면접 탭을 클릭했을 때 면접 엔티티를 호출하여 보여주는 방식

2024-10-20 14:06 UTC, Xim-ya commented
추가적으로 문의 주신 내용 코멘트 남깁니다~

> ### 1. Job 과 JobGroup 두가지 동일한 enum 이 있던데 하나는 지워도 되는걸까요
으.. 왜 이렇게 구성되어 있는지 모르겠는데 하나로 통일해주시면 좋을 것 같아요. 기존 Job enum을 제거해주시면 될 것 같습니다!


> ### 2. 폴더 구조 괜찮은지, 네이밍 괜찮은지 한번 봐주셨으면 합니다.
폴더 구조, 네이밍 좋습니다! 다만 feature 폴더를 study_content에서 조금 더 간단하게 content로 변경해주시는것도 좋을것 같아요.


> ### 3. 속도를 위하여 Overview, Detail을 각각 다른 도큐먼트로 저장하고, 정합을 위해 Cloud Functions를 사용하는 것에 관한 의견
네 좋습니다! 근데 Cloud Functions을 상세적으로 어떻게 사용하실건지 나중에 공유해주시면 좋을것 같습니다~

2024-10-21 01:51 UTC, Yellowtoast commented on lib/features/study_contents/repositories/entities/video_contents_author_entity.dart
> +}
사실 VideoContentsAuthorEntity와 ContentsAuthorEntity 이 완전히 동일하지는 않습니다! subscribers 이라는 하나의 변수정도? 달라지는데요, 추후에 기술 블로그가 추가되는 것을 고려하여 + 기술블로그가 추가된다면 컨텐츠 디테일 페이지가 비슷한 UI로 나올것을 대비하여 동일 화면을 사용할 수 있도록 추가하였습니다! 다만 기술블로그가 추가될 확률이 적다면 굳이 추상화 하지 않고 하나의 클래스로 통일해도 괜찮을 것 같습니다.

2024-10-27 07:44 UTC, Yellowtoast commented on lib/features/study_contents/repositories/entities/video_contents_detail_entity.dart
> +}
아래 커밋에서 반영하였습니다! 확인 부탁드립니다.
https://github.com/MakeFrog/TechTalk/pull/138/commits/0f4d8f885ec04684b62b50ee29d65619719b8b44

2024-10-27 07:45 UTC, Yellowtoast commented
해주님꼐서 피드백 주신 부분 반영하여 다시 푸시하였습니다.
또한 기존에 혼용하여 사용하던 Job enum을 제거하고 JobGroup으로 통일하였습니다.
JobGroup이 사용처가 많이 해당 enum을 유지하였으나, enum 형식의 변경이 필요할 것 같습니다.
혹시 해당 부분 파싱으로 사용하는 곳이 있을까 하여 우선 유지하였습니다!
확인 부탁드립니다~

2024-10-27 10:48 UTC, Xim-ya commented
> 해주님께서 피드백 주신 부분 반영하여 다시 푸시 하였습니다. 또한 기존에 혼용하여 사용하던 Job enum을 제거하고 JobGroup으로 통일하였습니다. JobGroup이 사용처가 많이 해당 enum을 유지하였으나, enum 형식의 변경이 필요할 것 같습니다. 혹시 해당 부분 파싱으로 사용하는 곳이 있을까 하여 우선 유지하였습니다! 확인 부탁드립니다~

enum에서 어떤 형식이 변경한지 알려주시면 확인 해보겠습니다~

> 
> 그리고 또 드리고 싶은 질문이 있습니다. entity를 사용하실 때, 불변성을 유지하기 위하여 어떤 방식을 선호하시는지 궁금합니다! 현재는 일일이 copyWith, == 이 구현이 되어있는 것으로 알고 있는데요!
> 
> 1. Equatable 라이브러리를 따로 사용하시지 않은 이유가 있을까요?
> 2. Freezed로 생성하여 사용하시는 것을 선호하시는지, 아니면 Equatable만 따로 사용하시는 것을 선호하시는지?
> 
> 개인적으로는 라이브러리 의존성을 낮추기 위해 Entity에만 equatable을 붙이거나 직접 구현하고, Dto에는 JsonSerializable만 붙이는 쪽을 선호하긴 하는데요. 어느 쪽을 선호하시는지 의견이 궁금합니다.

불변성을 유지하기 위해서 Freezed를 사용하는편인데, 문제는 Freezed를 사용하면 상속 기능이 제한되어서 entity 단에서는 직접 copywith, == 코드를 사용했습니다. Equatable을 사용해보지 않았지만 아마 비슷한 문제가 있을것 같고요.

그래서 'dart data class'라는 snippet을 이용하여 불변성 관련 코드를 작성했었습니다.

결론은 상속 구조를 설계할 수 없기 때문에 freezed, equtable 패키지를 사용 안하는 방향으로 설계한건데,
다시 고민해보니, 상속이 필요한 entity class에만 이렇게 설정해도 될 것 같다는 생각이 드네요.

앞으로 지혜님이 말씀해주신 방향으로 데이터 클래스를 구성해주셔도 좋을것 같습니다~

2024-10-27 10:49 UTC, Xim-ya approved these changes

2024-11-03 06:46 UTC, merged