Feat: [영상상세페이지] 유튜브 api 데이터 세팅 로직 구현
MakeFrog/TechTalk pull request #144
Opened 2024-11-03 10:25 UTC by Yellowtoast

## 📝 변경 내용
* 영상 메인, 상세 라우트 세팅
* 영상 상세 페이지에서 유튜브 api정보 불러오는 기능 구현

<br>

## 📌 참고 사항
* UI가 온전히 완성되어있지 않고, youtube api를 사용하여 뿌려주는 부분만 임시로 구현되어 있습니다.
* 해당 부분 빠르게 피드백 받은 후에, 영상 메인화면과 상세에 사용되는 데이터 firebase 세팅 관련하여 논의 예정

<br>

## 👥 리뷰어
* @Xim-ya @yundal8755

2024-11-10 06:19 UTC, Xim-ya requested changes

2024-11-10 06:19 UTC, Xim-ya commented on lib/presentation/pages/contents/contents_detail_page.dart
> +}
## P4 enum 소스 파일 별도 분리

enum은 다른 소스파일로 분리하는건 어떤가요?

제 생각하는 폴더 구조는 아래오와 같습니다.

- presentation
   - pages
      - (section)
          - home
             - home_page.dart
             - home_event.dart
             - home_state.dart
               - local_widgets  
               - constants
                  - tab_type.enum.dart // <-- 여기 !!!!

2024-11-10 06:19 UTC, Xim-ya commented on lib/presentation/pages/contents/contents_detail_page.dart
> +    final videoData = ref.watch(youtubeVideoDataProvider(overview.contentsId));
## P2 State Mixin Class 적용

provider의 상태를 전달 받을 때 `State Mixin Class` 라는 모듈로 한번 감싸주시는건 어떤가요? 기존 페이지에는 모두 동일하게 state, event mixin class로 구성되어 있습니다. 

이렇게 mixin class를 기반으로 provider의 상태에 접근할 수 있는 구조로 구성하면 여러 이점이 있는데,
관련해서 블로그 글을 작성했으니 참고해주시면 좋을 것 같습니다~
> https://medium.com/jobkorea-tech/flutter-riverpod을-맛있게-믹스인-하기-a7d2481396ff

2024-11-10 06:19 UTC, Xim-ya commented on lib/presentation/widgets/common/box/async_skeleton_widget_builder.dart
> +}
이렇게 모듈화하면 스켈레톤 로딩에 자연스러운 트랜지션을 편리하게 적용할 수 있겠네요 👍

2024-11-12 07:13 UTC, Yellowtoast commented on lib/presentation/pages/contents/contents_detail_page.dart
> +    final videoData = ref.watch(youtubeVideoDataProvider(overview.contentsId));
https://github.com/MakeFrog/TechTalk/pull/144/commits/c6b604a321fd5a9a4631eff2fd7bb24e5b56c3fd

해당 커밋에서 반영하였습니다!

2024-11-12 07:13 UTC, Yellowtoast commented on lib/presentation/pages/contents/contents_detail_page.dart
> +}
https://github.com/MakeFrog/TechTalk/pull/144/commits/c6b604a321fd5a9a4631eff2fd7bb24e5b56c3fd

해당 커밋에서 반영하였습니다!

2024-11-12 16:11 UTC, Xim-ya approved these changes

2024-11-13 10:48 UTC, yundal8755 approved these changes
구현 내용 확인했습니다 고생하셨어요!

2024-11-13 11:47 UTC, merged