[채팅 면접] QnaEntity 데이터 구조 설정
MakeFrog/TechTalk pull request #154
Opened 2024-11-24 14:01 UTC by Xim-ya

## 📝 변경 내용
- 이력서(+포트폴리오), 유튜브 콘텐츠 등의 면접 기능 다양화로 인해, 확장 가능한 QnaEntity  데이터 클래스 구조 설정.
```dart
abstract class BaseQnaEntity {
  /// 고유 id 값
  final String id;

  /// 질문
  final String question;

  /// 문답 유형
  final QnaType type;

  const BaseQnaEntity({
    required this.id,
    required this.question,
    required this.type,
  });
}
```
`BaseChatEntity`라는 기본 추상 클래스가 존재하고 각 유형의 entity 클래스가 해당 클래스를 extends 하는 형식
```dart
class ResumeQnaEntity extends BaseQnaEntity {
  /// 평가 요소
  final String evaluationPoint;

  /// 하드스킬, 소프스킬 질문 타입
  final ResumeQuestionType questionType;

  const ResumeQnaEntity({
    required super.id,
    required super.question,
    required this.questionType,
    required this.evaluationPoint,
  }) : super(
          type: QnaType.resume,
        );
...

```

<br>

## 👥 리뷰어
@Yellowtoast , @yundal8755 

<br>

## 📌 기타 사항
@yundal8755  기본 이력서 qna entity 구조를 설정해두었으니, 이력서 기반 면접 질문을 생성하실 때 참고해주시면 될 것 같습니다~
>아래 경로 있는 소스파일을 참고해주세요 :)
[lib/features/chat/repositories/entities/resume_qna_entity.dart](https://github.com/MakeFrog/TechTalk/compare/feature/progress-on-dynamic-qna-entity-setting?expand=1#diff-4ac320be31c3ed6583b3e67986b7133ffe5b517a665230e6d3cce2e726aa3e60)
<br>

2024-11-25 11:38 UTC, Yellowtoast requested changes

2024-11-25 11:38 UTC, Yellowtoast commented on lib/features/chat/repositories/entities/resume_qna_entity.dart
> +class ResumeQnaEntity extends BaseQnaEntity {
P2. 혹시 implements 대신 extends를 사용하신 이유가 있으실까요?

2024-11-25 11:38 UTC, Yellowtoast commented on lib/features/chat/repositories/entities/base_qna_entity.dart
> +abstract class BaseQnaEntity {
P3. sealed class로 선언하면, switch-case 문에서 관련 entity를 빠짐 없이 대응할 수 있는 장점도 있을 것 같은데, 또 abstract class 를 사용하신 이유도 있을 것 같아서, 궁금합니다!

2024-11-25 11:38 UTC, Yellowtoast commented on lib/features/chat/repositories/entities/chat_qna_entity.dart
> +  final CommonQnaEntity qna; // 문답
P3. CommonQnaEntity 외에도, 다른 QnaEntity 종류들도 ChatQnaEntity 에 들어갈 수 있을 것 같은데, 혹시 BaseQnaEntity 대신에 CommonQnaEntity 를 지정하신 이유가 있을까요~? ㅎㅎ

2024-11-26 15:21 UTC, yundal8755 reviewed
고생하셨습니다! 저는 기존의 Base로 시작하는 추상 클래스(BasePage, BaseUseCase)랑 비슷한 맥락으로 BaseQnaEntity 구조를 설정한 걸로 이해했는데, 제가 이해한 게 맞을까요? 지혜님이 리뷰 남겨주신 걸 보니 답변이 궁금하네요~

2024-11-26 15:21 UTC, yundal8755 commented on lib/features/chat/repositories/entities/resume_qna_entity.dart
> +class ResumeQnaEntity extends BaseQnaEntity {
저는 BasePage, BaseUseCase와 같은 맥락으로 BaseQnaEntity를 추상 클래스로 만들어서 다른 하위 Entity에 extends를 사용한 거라고 생각했는데, 이 부분에 대해 두 분은 어떻게 생각하시나요?

2024-11-26 15:21 UTC, Xim-ya commented on lib/features/chat/repositories/entities/resume_qna_entity.dart
> +class ResumeQnaEntity extends BaseQnaEntity {
음.. `BaseQnaEntity`가 인터페이스 역할만 한다면, 가독성인 측면에서 `implements`도 괜찮다고 생각하는데요. 

**다만 implements를 사용하면, 추상 클래스나 인터페이스에 정의된 모든 속성과 메서드를 구현하는 클래스에서 반드시 명시적으로 재정의해주어야 하기 때문에 extends를 사용하는게 괜찮다고 생각했습니다.** 

예를들어, 각 BaseQnaEntity를 상속 받는 모든 하위 클래스에는 id값을 uuid로 초기화 시켜주는 조건이 필요하다고 가정해보겠습니다.

```dart
abstract class BaseQnaEntity {
  /// 고유 id 값
  final String id;

  /// 질문
  final String question;

  /// 문답 유형
  final QnaType type;

  BaseQnaEntity({
    String? passedId,
    required this.question,
    required this.type,
  }) : id = passedId ?? const Uuid().v1();
}
```
그렇다면 이렇게 슈퍼클래스의 생성자에 id멤버 변수로 uuid값으로 초기화 시켜주는 로직을 지정해줄 수 있습니다.

만약 자식 클래스가 `extends`한다면 부모의 id값 초기화 로직을 그대로 상속 받을 수 있지만,
반대로 `implements` 한다면 구현하는 클래스에서 해당 id값 초기화 로직을 재정의 해주어야 하기 때문에 일정 부분 번거로움이 발생합니다.


물론 지금 구조에서는 부모 클래스에서 이렇게 재정의하는 로직이 없기 때문에 괜찮지만, 추후 이력서 관련 기능을 개발하면서 필요할 수 있을 것 같아서 현재 적용된 방식을 유지해도 괜찮을 것 같아요!

> 참고로 이러한 이유로 현재 BaseChatEntity라는 추상 클래스도 extends하는 방식을 채택하고 있습니다.

2024-11-26 15:35 UTC, Xim-ya commented on lib/features/chat/repositories/entities/base_qna_entity.dart
> +abstract class BaseQnaEntity {
sealed class를 사용하냐 아니면 abstract + enum을 이용할까 약간 고민을 했었는데요.

둘 다 괜찮지만, 개인적으로 abstract + enum 방식이 조금 더 예뻐(?) 보였습니다.

추후에 label text나 아이콘 같은 리소스를 qna 타입에 따라 노출해야될 필요가 있을 것 같은데요.

```dart
enum QnaType {
  common('단골질문!', Assets.common), // 단골 면접 질문,
  resume('이력서 질문!',  Assets.resume), // 이력서(+포트폴리오) 면접 질문
  youtube('영상 학슥 질문', Assets.youtube); // 유튜브 콘텐츠 기발 면접 질문

  final String label;
  final String iconPath;

  const QnaType(this.label, this.iconPath);
}
```
 이때  enum으로 타입을 지정하면, 위 코드처럼 필요한 리소스를 eum에서 관리할 수 있게 됩니다.

물론 sealed 클래스를 사용하고 각 자식 클래스의 멤버 변수에 해당 리소스를 명시할 수 도 있겠지만... 데이터 클래스에는 데이터만 노출(?) 되는 형태가 좋아 보인다고 생각하고 있어 선택하지 않았습니다.

하지만 말씀하신대로 sealed를 이용하면 쉽게 switch문을 적용할 수 이점이 있는데요.
이걸 보완하기 위해 저는 enum에 직접 커스텀 switch 문과 유사하게 case 별로 특정 동작을 실행하거나 리턴할 수 있는 메소드를 주로 만들어 둡니다.

```dart
enum QnaType {
  common('단골질문!', Assets.common), // 단골 면접 질문,
  resume('이력서 질문!', Assets.resume), // 이력서(+포트폴리오) 면접 질문
  youtube('영상 학슥 질문', Assets.youtube); // 유튜브 콘텐츠 기발 면접 질문

  final String label;
  final String iconPath;

  const QnaType(this.label, this.iconPath);


/// 여기!
  R branch<R>({
    required R Function() common,
    required R Function() resume,
    required R Function() youtube,
  }) {
    switch (this) {
      case QnaType.common:
        return common();
      case QnaType.resume:
        return resume();
      case QnaType.youtube:
        return youtube();
      default:
        throw Exception('잘못된 enum 값: $branch');
    }
  }
}


/// 사용 예시

   final type = someQnaType;

    type.branch(
      common: () {},
      resume: () {},
      youtube: () {},
    );
```


각 장단점이 있어보이는데, 이러한 방식은 극히 제 개인적인 취향인 것 같아요 ㅎㅎㅎ

2024-11-26 15:37 UTC, Xim-ya commented on lib/features/chat/repositories/entities/chat_qna_entity.dart
> +  final CommonQnaEntity qna; // 문답
넵 맞습니다. 기존 QnaEntity가 CommonQnaEntity로 변경되면서 일단 저렇게 적용되었어요!

나중에 이력서 채팅 기능 작성하면서 말씀하신 방향으로 작업할 예정입니다!

2024-11-26 15:51 UTC, Xim-ya commented
> 고생하셨습니다! 저는 기존의 Base로 시작하는 추상 클래스(BasePage, BaseUseCase)랑 비슷한 맥락으로 BaseQnaEntity 구조를 설정한 걸로 이해했는데, 제가 이해한 게 맞을까요? 지혜님이 리뷰 남겨주신 걸 보니 답변이 궁금하네요~

네 동일한 구조로 되어 있다고 생각하시면 됩니다. 제가 implements가 아닌 extends를 사용한 이유는 지혜님 피드백 댓글로 확인해주시면 좋을 것 같습니다!

조금 더 느낌적인 이해를 돕기 위해 extends implements 예시를 하나 첨부합니다! 

```dart
abstract class Vehicle implements HeatSeatOption {
  final String name;
  final int numberOfWheels;

  Vehicle(this.name, this.numberOfWheels);
}

class Car extends Vehicle {
  final bool hasSupportSunRoof;

  Car(
    super.name,
    super.numberOfWheels,
    this.hasSupportSunRoof,
    this.temperature,
  );

  @override
  final double temperature;

  @override
  void turnOnHeatedSeat() {
    // TODO: implement turnOnHeatedSeat
  }
}

/// 온열 시트 기능 ㅎㅎ
abstract class HeatSeatOption {
  final double temperature;

  void turnOnHeatedSeat();

  HeatSeatOption(this.temperature);
}

```

2024-11-27 10:37 UTC, Yellowtoast approved these changes
정말 수고 많으셨습니다!!!

2024-11-27 11:03 UTC, yundal8755 approved these changes
고생하셨어요~!

2024-11-27 11:10 UTC, merged