[채팅 면접] 이력서 면접 질문 생성 프롬프트 제작
MakeFrog/TechTalk pull request #160
Opened 2024-12-01 17:37 UTC by yundal8755

## 📝 변경 내용

이력서 면접 질문 생성 프롬프팅 명세에 알맞게 use_case를 구현하고 테스트를 해보았습니다.

https://github.com/MakeFrog/TechTalk/issues/153

**구현시 고려 사항**
- [x]  이력서/포트폴리오 정보를 파일 혹은 텍스트 형태로 프롬프트에 제공할 수 있어야 한다.
- [x]  프롬프팅 usecase의 리턴 값은 ResumeEntity의 리스트가 되어야 한다.
- [x]  프롬프팅의 결과로 json을 받되, 클래스 형식(ResumeEntity)으로 변환되어야 한다.
- [x]  단순 정보 생성이므로 단일 응답값 리턴으로 구현된다.

**확인 필요 사항**
- [x]  이력서/포트폴리오를 파일 형태로 api에 전송 가능한지 여부 확인
- [x]  파일 형태로 제공 가능하다면, 사용되는 토큰의 양 체크 필요함. (요금체크)

**기존 프롬프팅 명세 외에 추가로 테스트한 내용**
- [x]  GPT의 응답을 만드는 메서드인 onComplete와 onChatComplete의 차이점 비교
- [x]  ChatModel별 성능 비교 (4, 4o, 4oMini, 4oPreview의 토큰 사용량, 출력 시간 등)
<br>

### 주요 내용
**1️⃣ 프롬프팅시 File 객체를 첨부 가능한가? (예시 : PDF 파일)**
- 기존의 학습 모델을 추가로 학습시키기 위한 Fine-tuning라는 목적을 위해 jsonl 형태의 파일을 첨부하는 것은 가능합니다.
- 하지만 테크톡의 목적이었던 유저의 이력서와 포트폴리오 PDF 파일을 첨부하여 프롬프팅하는 것은 불가능합니다.
- 이는 곧 PDF 파일의 텍스트를 직접 추출하여 프롬프팅해야 함을 의미합니다.
<br>

**2️⃣ PDF 파일의 텍스트를 어떤 방식으로 추출할 것인가?**
- pdf 파일은 텍스트 기반과 이미지 기반으로 분류할 수 있습니다.
- pdf 파일이 텍스트 기반일 경우, pdf_text 패키지를 사용하여 텍스트를 추출할 수 있습니다.
- 그러나 유저가 첨부한 파일이 이미지 기반의 pdf 파일일 경우, ocr을 통해 텍스트를 추출해야 합니다.
- 현재 ocr 방식의 경우, 이미지 파일만 텍스트로 추출이 가능하기 때문에 불가피하게 pdf 파일을 이미지로 변환하는 작업도 수행해야 합니다.
- pdf to txt을 적용한 내용은 현재 PR에는 반영되어 있지 않습니다. 자세한 내용은 하단의 **기타 사항**에 작성했으니 참고 부탁드립니다.
<br>

**3️⃣ GPT의 응답을 만드는 메서드인 onComplete와 onChatComplete의 차이점 비교**
- `onComplete` 는 4와 같은 최신 모델은 지원하지 않으며, 아주 간단한 Q&A나 짧은 텍스트 생성에 유리합니다.
- `onChatComplete` 는 4 이상의 최신 모델을 지원하며, 시스템 메시지와 사용자 입력을 조합하여 문맥 기반의 결과를 제공합니다.
- 사용자의 이력서와 포트폴리오라는 인풋에 올바른 문맥의 질문을 빠르게 생성하기에는 onChatComplete가 유리하기에, 아래와 같이 사용했습니다.

```dart
      // GPT 응답 대기
      final response = await OpenAI.instance.onChatCompletion(
        request: ChatCompleteText(
          messages: createResumeChatMessage(request),
          maxToken: 1000,
          temperature: 0.5,
          user: FirebaseAuth.instance.currentUser!.uid,
          model: Gpt4oMini2024ChatModel(),
        ),
      );
```
<br>

**4️⃣ ChatModel별 성능 비교 (4, 4o, 4oMini, 4oPreview의 토큰 사용량, 출력 시간 등)**
- 모두 동일한 조건에서 간단하게 성능을 비교한 결과, 4와 4oPreview는 프롬프팅 결과가 매우 늦게 나옵니다.
- 4o, 4oMini의 경우, SetAiResumeQuestionUseCase의 프롬프팅을 기준으로 4~7초 내외의 결과를 출력합니다.
- 현재 4o와 4oMini의 프롬프팅 결과에 대한 유의미한 성능 차이는 느끼지 못하고 있습니다.

`4o 출력 결과`
![image](https://github.com/user-attachments/assets/bb362d5b-a476-428b-8c8e-36d434958ec6)
<br>

## 👥 리뷰어
@Xim-ya @Yellowtoast 
<br>

## 📌 기타 사항
**전달 사항**
- pdf to txt를 지원하는 패키지를 테크톡에 사용하기 위해서 해결해야 하는 문제가 있습니다. pdf_text 패키지에서 사용하는 http 라이브러리의 버전이 현재 테크톡에서 사용하는 특정 패키지의 http 버전과 맞지 않아 pub get 단계에서 에러가 발생합니다. 이 부분은 이력서 관리 기능을 구현하면서 해결해보도록 하겠습니다.

**의논해보고 싶은 점**
- 만약 유저가 첨부한 PDF의 내용이 텍스트가 아닌 이미지 기반일 경우, OCR을 도입해야 할텐데, 이 부분의 경우 예외처리의 복잡도가 기존보다 높아지고 플랫폼별로 설정을 해야 할 부분이 더 많이 생깁니다. 일단 OCR 기능을 도입할 것인가에 대해 의논해보면 좋을 것 같습니다.

2024-12-02 01:16 UTC, Yellowtoast requested changes

2024-12-02 01:16 UTC, Yellowtoast commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +      {"role": "user", "content": "위 내용을 바탕으로 질문을 작성해주세요."},
p3. user를 빼도 결과값에는 큰 차이가 없을 것 같은데, 혹시 체크 한번 해보셨을까요?

2024-12-02 01:16 UTC, Yellowtoast commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +      final parsedResponse = jsonDecode(response!.choices[0].message!.content);
p2. response나 message가 null일 경우에 대한 예외 처리가 따로 되어있을까요? 혹시 null이 발생하면 어떻게 동작하게 될까요~?

2024-12-02 01:16 UTC, Yellowtoast commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +                  ? "hardSkill"
p4. hardSkill이나 softSkill을 String으로 지정하지 않아도, ResumeQuestionType enum 내부에 선언해서 바로 String을 사용할 수 있지 않을까요? 아래에서 str 선언한 방식처럼요!

```dart
enum AnswerState {
  initial('[i]', ''),
  loading('[l]', ''),
  error('[e]', ''),
  correct('[c]', LocaleKeys.common_responseResult_correct),
  wrong('[w]', LocaleKeys.common_responseResult_incorrect),
  inappropriate('[x]', LocaleKeys.common_responseResult_incorrect);

  final String tag;
  final String str;

  const AnswerState(this.tag, this.str);

  bool get isCompleted => this == AnswerState.wrong || this == AnswerState.correct;
  bool get isInitial => this == AnswerState.initial;
  bool get isLoading => this == AnswerState.loading;
  bool get isError => this == AnswerState.error;
  bool get isCorrect => this == AnswerState.correct;
  bool get isWrong => this == AnswerState.wrong;
  bool get isWrongOrInappropriate => this == AnswerState.wrong || this == AnswerState.inappropriate;
  bool get isInappropriate => this == AnswerState.inappropriate;

  static AnswerState getStateById(String id) {
    return values.firstWhere(
      (state) => state.tag == id,
      orElse: () => throw Exception('Unexpected Topic Id Value'),
    );
  }
}

```

2024-12-02 01:16 UTC, Yellowtoast commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +          messages: createResumeChatMessage(request),
p2. 해당 함수는 외부에서 사용하는 것이 아니라면 private하게 선언해도 좋을 것 같습니다~

2024-12-02 01:16 UTC, Yellowtoast commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +              questionType: json['type'] == 'hardSkill'
p2. 아래 리뷰에서 말씀드린 것처럼 enum 내부에도 str 파싱 함수를 놓고, ResumeQnaEntity 클래스에서 json 파싱 함수를 구현하시는 쪽이 좋을 것 같습니다!

2024-12-02 01:16 UTC, Yellowtoast commented on lib/presentation/pages/home/home_event.dart
> +        (resumeContent: resumeContent, portfolioContent: portfolioContent);
p3. GetResumeParam 에서 각 resumeContent이나 portfolioContent 은 옵셔널인가요? 둘다 반드시 들어가야 하는 값인건지 궁금합니다! ㅎㅎ

2024-12-02 01:16 UTC, Yellowtoast commented
PR 내용을 정말 깔끔하게 정리해주셔서 이해하기 훨씬 쉬웠네요. 감사합니다!

2024-12-03 15:38 UTC, Xim-ya approved these changes
고생하셨습니다!

PR을 꼼꼼히 적어주셔서 어떠한 고민을 하고 계신지 쉽게 이해할 수 있었습니다 👍 

일단 open ai를 이용하 File Upload를 할 수 있는 방법에 대해 찾아봤는데, 완전히 불가능한건 아니지만, 업로드한 파일을 기반으로 일반적인 chat 또는 completion을 통해 propmt를 설정하기는 어려워 보이네요. 공식문서를 살펴보니 assistant를 사용해야 하는데, 이 방식이 얼마만큼 퀄리티나 퍼포먼스를 보장할지는 의문이고요.

말씀해주신 방법처럼 ocr이후 출력된 텍스트를 활용하는 방안을 고려해야거나,
이력서 질문 생성은 gemini를 이용해보는것도 괜찮을 것 같습니다.

```dart
void main() async {
  const geminiApiKey = 'your_api_key_here';
  final genaiService = GenaiClient(geminiApiKey: geminiApiKey);

  try {
    final testFile = File('');
    final data = await genaiService.promptDocument(
      'file_name', 
      'pdf', 
      testFile.readAsBytesSync(), 
      'Your prompt',
    );
    print(data.text);
  } catch (e) {
    print('Error: $e');
  }
}
```

위 코드와 같이 gemini에서는 pdf 첨부와 prompt를 설정을 쉽게 할 수 있어요. 한번 검토 부탁드리겠습니다!

2024-12-03 15:38 UTC, Xim-ya commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
## P4 useCase 네이밍

면접 질문을 생성하는 useCase이기 때문에 create이라는 워딩을 포함시키는건 어떤가요?

> CreateResumeBasedQuestionUseCase
> CreateResumeQuestionUseCase

2024-12-03 15:38 UTC, Xim-ya commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +  질문 작성 시 지원자가 수행한 프로젝트, 해결한 도전 과제, 적용한 기술과 관련된 맥락을 반영하세요.
## P1 예외처리 요구사항 
지혜님이 따로 정리해주신 요구사항에는 포함되어 있지는 않지만,
> - 이력서 or 포트폴리오가 아닌 경우
> - 개발자 이력서(포트폴리오)가 아닌 경우
위와 같이 유효한 이력서 아닌 경우 필요한 예외처리 작업을 해주셔야 할 것 같습니다. 

추가적으로 생성된 질문이 최소 개수를 충죽하지 못할 경우에도 마찬가지 이고요.

이 작업을 어떠한 프로세스로 거쳐 판단할지 고민해주시면 좋을 것 같습니다 :)

> 해당 내용은 다음 PR에 반영해주셔도 괜찮습니다!

2024-12-04 10:14 UTC, yundal8755 commented on lib/features/chat/use_cases/set_ai_resume_question_use_case.dart
> +      {"role": "user", "content": "위 내용을 바탕으로 질문을 작성해주세요."},
방금 체크해봤는데, 큰 차이가 없네요 오히려 토큰 수가 전반적으로 줄어드는 효과가 있네요! user 부분은 빼도록 하겠습니다

2024-12-04 11:21 UTC, Yellowtoast approved these changes

2024-12-14 05:29 UTC, merged